DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
  id              SERIAL PRIMARY KEY,
  first_name           VARCHAR(100) NOT NULL,
  last_name  VARCHAR(100) NULL
);

DROP TABLE IF EXISTS IDIOM;
CREATE TABLE IDIOM (
  id              SERIAL PRIMARY KEY,
  description           VARCHAR(100) NOT NULL
);
